spring:
  r2dbc:
    url: r2dbc:postgresql://${postgres_host:localhost}:${postgres_port:5432}/${postgres_db:reactive-chat}
    username: ${postgres_user:user}
    password: ${postgres_password:password}
    pool:
      enabled: true
    properties:
      schema: ${postgres_schema:public}


  liquibase:
    enabled: true
    url: jdbc:postgresql://${postgres_host:localhost}:${postgres_port:5432}/${postgres_db:reactive-chat}
    default-schema: ${postgres_schema:public}
    user: ${postgres_user:user}
    password: ${postgres_password:password}
    driver-class-name: org.postgresql.Driver