spring:
  webflux:
    base-path: ${CONTEXT_PATH:}
  r2dbc:
    url: r2dbc:h2:mem:///reactive-chat
    username: sa
    password:

#  liquibase:
#    enabled: true
#    url: jdbc:h2:mem:reactive-chat
#    user: sa
#    password:
#    driver-class-name: org.h2.Driver

  rsocket:
    server:
      transport: websocket
      mapping-path: "/ws"


logging:
  level:
    root: warn
    com.github.scalvetr.reactivechat: debug
    io.rsocket: debug
    org.springframework.r2dbc: debug
    io.r2dbc.postgresql: debug
