apiVersion: apps/v1
kind: StatefulSet
#https://stackoverflow.com/questions/47516355/multi-broker-kafka-on-kubernetes-how-to-set-kafka-advertised-host-name
metadata:
  name: kafka-broker
spec:
  selector:
    matchLabels:
      app: kafka-broker
  serviceName: kafka-broker
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.12-2.5.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: BROKER_ID_COMMAND
              value: "hostname | awk -F '-' '{print $2}'"
            - name: KAFKA_CREATE_TOPICS
              value: messages-in:2:1
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "export KAFKA_BROKER_ID=${HOSTNAME##*-}"